dist: bionic
language: python
python:
  - "3.7"
cache: pip
install:
  - 'pip install -e .[all]'
script:
  - 'flake8'
  - 'coverage run -m unittest discover tests'
  - 'sphinx-build docs/source docs/build/html'
after_success:
  - 'codecov'

branches:
  only:
    - master
